/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPENBRACKET = 1;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 2;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int VARIABLE = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "<VARIABLE>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<token of kind 9>",
  };

}
